spring:
  profiles:
    active: local

---
spring:
  profiles: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: testAdmin
    password: testPassword

grpc:
  port: 6565